project:
  type: website

website:
  title: "Minimum Viable Blog"
  description: Course Projects for STA9750 Spring 2025 at Baruch College
  site-url: "https://allcr.github.io/STA9750-2025-SPRING/"
  navbar:
    background: primary
    search: false
    right:
      - about.qmd
      - icon: github
        href: https://github.com/allcr/STA9750-2025-SPRING
    
format:
  html:
    theme: yeti
    toc: true
    fig-format: png
    fig-dpi: 300

editor:
  mode: source
